version: "3.8"
services:
    postgres:
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: authentication
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    back-end:
        build:
            context: back-end
        depends_on:
            - postgres
        volumes:
            - ./back-end:/var/www/html
            - ./back-end/vendor:/var/www/html/vendor:cached
        tmpfs:
            - /var/www/html/storage:uid=33,gid=33
            - /var/www/html/storage/framework:uid=33,gid=33
            - /var/www/html/storage/framework/cache:uid=33,gid=33
            - /var/www/html/storage/framework/sessions:uid=33,gid=33
            - /var/www/html/storage/framework/views:uid=33,gid=33
            - /var/www/html/bootstrap/cache:uid=33,gid=33
        ports:
            - "8000:80"
    app:
        build: 
            context: app
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app
            - /app/node_modules/
        command: yarn start
        depends_on:
            - back-end
            - postgres
        stdin_open: true

# Not ready yet
    # native-app:
    #     build:
    #         context: nativeApp
    #         args:
    #             - NODE_ENV=development
    #     environment:
    #         - NODE_ENV=development
    #         - ADB_IP=192.168.6.155
    #     tty: true
    #     ports:
    #         - '19006:19006'
    #         - '19001:19001'
    #         - '19002:19002'
    #         - '19000:19000'
    #         - '80:80'
    #     volumes:
    #         - ./nativeApp:/opt/nativeApp:delegated
    #         - /nativeApp/node_modules/
    #     healthcheck:
    #         disable: true